import type { UserConfig } from "vite-plus";

const packageBuildInputs = () => [
  "src/**",
  "scripts/**",
  "tests/**",
  "*.json",
  "*.ts",
  { pattern: "pnpm-lock.yaml", base: "workspace" as const },
  { pattern: "pnpm-workspace.yaml", base: "workspace" as const },
];

const appTypecheckInputs = [
  "components/**",
  "electron/**",
  "src/**",
  "packages/*/src/**",
  "packages/*/package.json",
  "package.json",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "tsconfig*.json",
];

export const runConfig = {
  tasks: {
    "pkg:logging:build": {
      command: "vp pack",
      cwd: "packages/automation-logging",
      input: packageBuildInputs(),
      output: ["packages/automation-logging/dist/**"],
    },
    "pkg:axios:build": {
      command: "vp pack",
      cwd: "packages/axios",
      input: packageBuildInputs(),
      output: ["packages/axios/dist/**"],
    },
    "pkg:feishu:build": {
      command: "vp pack",
      cwd: "packages/feishu-notifier",
      input: packageBuildInputs(),
      output: ["packages/feishu-notifier/dist/**"],
    },
    "pkg:ai:build": {
      command: "vp pack",
      cwd: "packages/drama-ai",
      input: packageBuildInputs(),
      output: ["packages/drama-ai/dist/**"],
    },
    "pkg:wechat:build": {
      command: "vp pack",
      cwd: "packages/wechat-drama-automation",
      dependsOn: ["pkg:axios:build", "pkg:feishu:build", "pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/wechat-drama-automation/dist/**"],
    },
    "pkg:wechat-miniprogram:build": {
      command: "vp pack",
      cwd: "packages/wechat-miniprogram-drama-automation",
      dependsOn: ["pkg:axios:build", "pkg:feishu:build", "pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/wechat-miniprogram-drama-automation/dist/**"],
    },
    "pkg:meituan:build": {
      command: "vp pack",
      cwd: "packages/meituan-drama-automation",
      dependsOn: ["pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/meituan-drama-automation/dist/**"],
    },
    "pkg:kuaishou:build": {
      command: "pnpm run build",
      cwd: "packages/kuaishou-drama-automation",
      dependsOn: ["pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/kuaishou-drama-automation/dist/**"],
    },
    "pkg:qq:build": {
      command: "vp pack",
      cwd: "packages/qq-drama-automation",
      dependsOn: ["pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/qq-drama-automation/dist/**"],
    },
    "pkg:tencent-huolong:build": {
      command: "vp pack",
      cwd: "packages/tencent-huolong-drama-automation",
      dependsOn: ["pkg:ai:build", "pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/tencent-huolong-drama-automation/dist/**"],
    },
    "pkg:iqiyi:build": {
      command: "vp pack",
      cwd: "packages/iqiyi-drama-automation",
      dependsOn: ["pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/iqiyi-drama-automation/dist/**"],
    },
    "pkg:baidu-drama:build": {
      command: "vp pack",
      cwd: "packages/baidu-drama-automation",
      dependsOn: ["pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/baidu-drama-automation/dist/**"],
    },
    "pkg:pinduoduo:build": {
      command: "vp pack",
      cwd: "packages/pinduoduo-drama-automation",
      dependsOn: ["pkg:axios:build", "pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/pinduoduo-drama-automation/dist/**"],
    },
    "pkg:tiktok:build": {
      command: "vp pack",
      cwd: "packages/tiktok-drama-automation",
      dependsOn: ["pkg:feishu:build", "pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/tiktok-drama-automation/dist/**"],
    },
    "pkg:douyin:build": {
      command: "vp pack",
      cwd: "packages/douyin-drama-automation",
      dependsOn: ["pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/douyin-drama-automation/dist/**"],
    },
    "pkg:baidu:build": {
      command: "vp pack",
      cwd: "packages/baidu-netdisk-automation",
      dependsOn: ["pkg:logging:build"],
      input: packageBuildInputs(),
      output: ["packages/baidu-netdisk-automation/dist/**"],
    },
    "packages:build": {
      command: "node -e \"console.log('workspace packages built')\"",
      dependsOn: [
        "pkg:ai:build",
        "pkg:logging:build",
        "pkg:wechat:build",
        "pkg:wechat-miniprogram:build",
        "pkg:meituan:build",
        "pkg:kuaishou:build",
        "pkg:qq:build",
        "pkg:tencent-huolong:build",
        "pkg:iqiyi:build",
        "pkg:baidu-drama:build",
        "pkg:pinduoduo:build",
        "pkg:tiktok:build",
        "pkg:douyin:build",
        "pkg:baidu:build",
      ],
      output: [],
    },
    "pkg:wechat:check": {
      command: "tsc --noEmit",
      cwd: "packages/wechat-drama-automation",
      output: [],
    },
    "pkg:wechat-miniprogram:check": {
      command: "tsc --noEmit",
      cwd: "packages/wechat-miniprogram-drama-automation",
      output: [],
    },
    "pkg:logging:check": {
      command: "tsc --noEmit",
      cwd: "packages/automation-logging",
      output: [],
    },
    "pkg:ai:check": {
      command: "tsc --noEmit",
      cwd: "packages/drama-ai",
      output: [],
    },
    "pkg:meituan:check": {
      command: "tsc --noEmit",
      cwd: "packages/meituan-drama-automation",
      output: [],
    },
    "pkg:kuaishou:check": {
      command: "tsc --noEmit",
      cwd: "packages/kuaishou-drama-automation",
      output: [],
    },
    "pkg:pinduoduo:check": {
      command: "tsc --noEmit",
      cwd: "packages/pinduoduo-drama-automation",
      output: [],
    },
    "pkg:tiktok:check": {
      command: "tsc --noEmit",
      cwd: "packages/tiktok-drama-automation",
      output: [],
    },
    "pkg:douyin:check": {
      command: "tsc --noEmit",
      cwd: "packages/douyin-drama-automation",
      output: [],
    },
    "pkg:baidu:check": {
      command: "tsc --noEmit",
      cwd: "packages/baidu-netdisk-automation",
      output: [],
    },
    "pkg:qq:check": {
      command: "tsc --noEmit",
      cwd: "packages/qq-drama-automation",
      output: [],
    },
    "pkg:tencent-huolong:check": {
      command: "tsc --noEmit",
      cwd: "packages/tencent-huolong-drama-automation",
      output: [],
    },
    "pkg:iqiyi:check": {
      command: "tsc --noEmit",
      cwd: "packages/iqiyi-drama-automation",
      output: [],
    },
    "pkg:baidu-drama:check": {
      command: "tsc --noEmit",
      cwd: "packages/baidu-drama-automation",
      output: [],
    },
    "app:typecheck": {
      command: "tsc --noEmit",
      input: appTypecheckInputs,
      output: [],
    },
    "playwright:browsers": {
      command: "pnpm playwright:install-browsers",
      cache: false,
    },
    "app:build": {
      command: "vp build",
      dependsOn: ["packages:build", "playwright:browsers", "app:typecheck"],
      cache: false,
    },
  },
} satisfies UserConfig["run"];
