import type Database from "better-sqlite3"
import { createHash, randomUUID } from "node:crypto"

import { migrateTaobaoImportedTasks } from "./imported-tasks-schema"

export type TaobaoImportedTaskStatus =
  | "pending"
  | "downloading"
  | "uploading"
  | "succeeded"
  | "failed"

export type TaobaoImportedTask = {
  id: string
  originalTitle: string
  baiduPanResourceLink: string
  episodeCount: number
  sourceFileName: string
  sourceSheet: string
  sourceRow: number
  status: TaobaoImportedTaskStatus
  attempts: number
  errorMessage?: string
  dramaTag?: string
  episodeSummaries?: string[]
  synopsisText?: string
  synopsisSource?: string
  metadataGeneratedAt?: string
  createdAt: string
  updatedAt: string
}

export type TaobaoImportedTaskInput = Pick<
  TaobaoImportedTask,
  | "originalTitle"
  | "baiduPanResourceLink"
  | "episodeCount"
  | "sourceFileName"
  | "sourceSheet"
  | "sourceRow"
>

export type TaobaoImportedTaskSummary = Record<TaobaoImportedTaskStatus, number> & {
  total: number
}

type TaskRow = {
  id: string
  originalTitle: string
  baiduPanResourceLink: string
  episodeCount: number
  sourceFileName: string
  sourceSheet: string
  sourceRow: number
  status: TaobaoImportedTaskStatus
  attempts: number
  errorMessage: string | null
  dramaTag: string | null
  episodeSummariesJson: string | null
  synopsisText: string | null
  synopsisSource: string | null
  metadataGeneratedAt: string | null
  createdAt: string
  updatedAt: string
}

const selectedColumns = `
  id,
  original_title AS originalTitle,
  baidu_pan_resource_link AS baiduPanResourceLink,
  episode_count AS episodeCount,
  source_file_name AS sourceFileName,
  source_sheet AS sourceSheet,
  source_row AS sourceRow,
  status,
  attempts,
  error_message AS errorMessage,
  drama_tag AS dramaTag,
  episode_summaries_json AS episodeSummariesJson,
  synopsis_text AS synopsisText,
  synopsis_source AS synopsisSource,
  metadata_generated_at AS metadataGeneratedAt,
  created_at AS createdAt,
  updated_at AS updatedAt
`

function readTask(row: TaskRow): TaobaoImportedTask {
  let episodeSummaries: string[] | undefined
  if (row.episodeSummariesJson) {
    try {
      const parsed: unknown = JSON.parse(row.episodeSummariesJson)
      if (Array.isArray(parsed) && parsed.every((item) => typeof item === "string")) {
        episodeSummaries = parsed
      }
    } catch {
      // Invalid legacy cache is ignored and regenerated by the runtime.
    }
  }
  return {
    id: row.id,
    originalTitle: row.originalTitle,
    baiduPanResourceLink: row.baiduPanResourceLink,
    episodeCount: row.episodeCount,
    sourceFileName: row.sourceFileName,
    sourceSheet: row.sourceSheet,
    sourceRow: row.sourceRow,
    status: row.status,
    attempts: row.attempts,
    errorMessage: row.errorMessage ?? undefined,
    dramaTag: row.dramaTag ?? undefined,
    episodeSummaries,
    synopsisText: row.synopsisText ?? undefined,
    synopsisSource: row.synopsisSource ?? undefined,
    metadataGeneratedAt: row.metadataGeneratedAt ?? undefined,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  }
}

function dedupeKey(task: TaobaoImportedTaskInput) {
  return createHash("sha256")
    .update(task.originalTitle.trim())
    .update("\u0000")
    .update(task.baiduPanResourceLink.trim())
    .update("\u0000")
    .update(String(task.episodeCount))
    .digest("hex")
}

export class TaobaoImportedTasksRepository {
  private readonly database: Database.Database
  readonly databasePath: string

  constructor(database: Database.Database, databasePath = ":memory:") {
    this.database = database
    this.databasePath = databasePath
    migrateTaobaoImportedTasks(this.database)
  }

  close(): void {
    this.database.close()
  }

  importTasks(tasks: TaobaoImportedTaskInput[]): { imported: number; skipped: number } {
    const insert = this.database.prepare(`
      INSERT OR IGNORE INTO taobao_imported_upload_tasks (
        id, dedupe_key, original_title, baidu_pan_resource_link, episode_count,
        source_file_name, source_sheet, source_row, status, attempts,
        created_at, updated_at
      ) VALUES (
        @id, @dedupeKey, @originalTitle, @baiduPanResourceLink, @episodeCount,
        @sourceFileName, @sourceSheet, @sourceRow, 'pending', 0,
        @createdAt, @updatedAt
      )
    `)
    const transaction = this.database.transaction((inputs: TaobaoImportedTaskInput[]) => {
      const now = new Date().toISOString()
      let imported = 0
      for (const task of inputs) {
        imported += insert.run({
          ...task,
          id: randomUUID(),
          dedupeKey: dedupeKey(task),
          createdAt: now,
          updatedAt: now,
        }).changes
      }
      return { imported, skipped: inputs.length - imported }
    })
    return transaction(tasks)
  }

  list(): TaobaoImportedTask[] {
    const rows = this.database.prepare(`
      SELECT ${selectedColumns}
      FROM taobao_imported_upload_tasks
      ORDER BY created_at DESC, rowid DESC
    `).all() as TaskRow[]
    return rows.map(readTask)
  }

  summary(): TaobaoImportedTaskSummary {
    const rows = this.database.prepare(`
      SELECT status, COUNT(*) AS count
      FROM taobao_imported_upload_tasks
      GROUP BY status
    `).all() as Array<{ status: TaobaoImportedTaskStatus; count: number }>
    const summary: TaobaoImportedTaskSummary = {
      total: 0,
      pending: 0,
      downloading: 0,
      uploading: 0,
      succeeded: 0,
      failed: 0,
    }
    for (const row of rows) {
      const count = Number(row.count)
      summary[row.status] += count
      summary.total += count
    }
    return summary
  }

  claimNext(): TaobaoImportedTask | null {
    const transaction = this.database.transaction(() => {
      const row = this.database.prepare(`
        SELECT ${selectedColumns}
        FROM taobao_imported_upload_tasks
        WHERE status='pending'
        ORDER BY created_at ASC, rowid ASC
        LIMIT 1
      `).get() as TaskRow | undefined
      if (!row) return null
      const now = new Date().toISOString()
      this.database.prepare(`
        UPDATE taobao_imported_upload_tasks
        SET status='downloading',
            attempts=attempts+1,
            error_message=NULL,
            started_at=@now,
            finished_at=NULL,
            updated_at=@now
        WHERE id=@id AND status='pending'
      `).run({ id: row.id, now })
      return readTask({
        ...row,
        status: "downloading",
        attempts: row.attempts + 1,
        errorMessage: null,
        updatedAt: now,
      })
    })
    return transaction()
  }

  markProgress(id: string, status: "downloading" | "uploading"): void {
    const result = this.database.prepare(`
      UPDATE taobao_imported_upload_tasks
      SET status=@status, updated_at=@now
      WHERE id=@id AND status IN ('downloading', 'uploading')
    `).run({ id, status, now: new Date().toISOString() })
    if (result.changes === 0) throw new Error(`TAOBAO_DRAMA_IMPORTED_TASK_NOT_FOUND: ${id}`)
  }

  saveGeneratedMetadata(id: string, metadata: {
    dramaTag: string
    episodeSummaries: string[]
    synopsisText?: string
    synopsisSource?: string
  }): void {
    const now = new Date().toISOString()
    const result = this.database.prepare(`
      UPDATE taobao_imported_upload_tasks
      SET drama_tag=@dramaTag,
          episode_summaries_json=@episodeSummariesJson,
          synopsis_text=@synopsisText,
          synopsis_source=@synopsisSource,
          metadata_generated_at=@now,
          updated_at=@now
      WHERE id=@id AND status IN ('downloading', 'uploading')
    `).run({
      id,
      dramaTag: metadata.dramaTag,
      episodeSummariesJson: JSON.stringify(metadata.episodeSummaries),
      synopsisText: metadata.synopsisText ?? null,
      synopsisSource: metadata.synopsisSource ?? null,
      now,
    })
    if (result.changes === 0) throw new Error(`TAOBAO_DRAMA_IMPORTED_TASK_NOT_FOUND: ${id}`)
  }

  complete(id: string, success: boolean, errorMessage?: string): void {
    const result = this.database.prepare(`
      UPDATE taobao_imported_upload_tasks
      SET status=@status,
          error_message=@errorMessage,
          finished_at=@now,
          updated_at=@now
      WHERE id=@id AND status IN ('downloading', 'uploading')
    `).run({
      id,
      status: success ? "succeeded" : "failed",
      errorMessage: errorMessage ?? null,
      now: new Date().toISOString(),
    })
    if (result.changes === 0) throw new Error(`TAOBAO_DRAMA_IMPORTED_TASK_NOT_FOUND: ${id}`)
  }

  retry(id: string): boolean {
    return this.database.prepare(`
      UPDATE taobao_imported_upload_tasks
      SET status='pending',
          error_message=NULL,
          started_at=NULL,
          finished_at=NULL,
          updated_at=@now
      WHERE id=@id AND status='failed'
    `).run({ id, now: new Date().toISOString() }).changes > 0
  }

  recoverInterrupted(): number {
    return this.database.prepare(`
      UPDATE taobao_imported_upload_tasks
      SET status='pending',
          error_message='上次运行中断，已自动重新排队',
          started_at=NULL,
          finished_at=NULL,
          updated_at=@now
      WHERE status IN ('downloading', 'uploading')
    `).run({ now: new Date().toISOString() }).changes
  }
}
